name: postgres_driver_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  async: ^2.11.0
  buffer: ^1.2.3
  crypto: ^3.0.3
  sasl_scram: ^0.1.1
  stream_channel: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
