name: websocket_app
version: 1.0.0

environment:
  sdk: ^3.2.4

dependencies:
  json_annotation: ^4.8.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
